import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Rubik } from 'next/font/google'
import { ModalProvider } from '@/components/ModalContext'; // Импортируем провайдер для модалки
import "./globals.css";
import "./register/RegisterPage.module.css";

// Инициализация шрифтов
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rubik = Rubik({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'], // только нужные веса
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${rubik.variable} ${geistMono.variable} antialiased`}
      >
        {/* Оборачиваем приложение в ModalProvider */}
        <ModalProvider>
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
